[package]
name = "steel-postprocess"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
steel-core = { path = "../steel-core" }
steel-plugins = { path = "../steel-plugins" }
ndarray = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
