//! Cross-validation of `BaryonicPipeline::evolve` against the code it
//! is a port of.
//!
//! The expected values below are **measurements of the committed
//! Cython**, not snapshots of the Rust: they are produced by
//! `Scripts/Validation/reference_baryonic.py`, which drives
//! `Functions_c.pyx::Starformation_c` itself on this exact fixture, fed
//! the Rust's own `age(z)` grid so the comparison isolates the baryonic
//! pipeline from the cosmology port (validated separately in M2).
//!
//! # The one place the two deliberately disagree
//!
//! `Functions.py::StarFormation` computes the gas ceiling as
//! `MaxGas = np.power(10, GetGasMass(...))` — a **linear** mass in Msun,
//! of order 4e9 — and `Starformation_c` then tests it as
//!
//! ```text
//! if SM_new > 0:
//!     if c_log10(SM_new) > MaxGas[k]:   # log10 compared against ~4e9
//!         SFR = c_pow(10, M_out[k,i]-12.0)
//! ```
//!
//! `log10(SM_new)` cannot exceed ~12 for any physical stellar mass, so
//! the test is never true and **the gas supply never limits star
//! formation in the Python**. The whole `GetGasMass`/`GetMaxGasMass`
//! machinery is inert. (`Starformation_c` also uses `MaxGas` *linearly*
//! four lines earlier, when filling its unused `GasMass` array, so it
//! contradicts itself within one function.)
//!
//! The Rust keeps the ceiling in log throughout and the cap engages, as
//! intended. So the tests here come in two parts: with the cap
//! neutralised the two implementations agree to ~1e-9 step for step,
//! which validates the port; with it live the Rust suppresses growth,
//! which is the intended physics. See `docs/PORT_CORRECTIONS.md` A6.

use rand::rngs::StdRng;
use rand::RngCore;
use rand::SeedableRng;

use steel_core::accretion::AccretionContext;
use steel_core::baryonic::{BaryonicPipeline, SatelliteState, Timeline};
use steel_core::cosmology::{Cosmology, MassDefinition};
use steel_core::gas::GasMassModel;
use steel_core::halo_growth::GrowthTrack;
use steel_plugins::{Cattaneo11, Planck15, StewartScaling, TomczakFormSfr, Wetzel13};

/// A gas model with no ceiling, reproducing the Python's dead cap so
/// the rest of the pipeline can be compared step for step.
struct UncappedGas;

impl GasMassModel for UncappedGas {
    fn max_gas_mass(&self, _log_halo_mass: f64) -> f64 {
        f64::INFINITY
    }
    fn gas_mass(&self, _log_sfr: f64, _log_halo_mass: f64, _rng: Option<&mut dyn RngCore>) -> f64 {
        f64::INFINITY
    }
}

fn build_timeline(cosmo: &Planck15) -> Timeline {
    let z: Vec<f64> = (0..11).map(|i| 1.0 - i as f64 * 0.05).collect();
    let t: Vec<f64> = z.iter().map(|&zi| cosmo.age(zi)).collect();
    let mut dt: Vec<f64> = t.windows(2).map(|w| w[1] - w[0]).collect();
    dt.push(*dt.last().unwrap());
    // `t_dyn_friction` must exceed the timeline's own span (2.74 Gyr
    // here), otherwise the fixture describes a satellite still infalling
    // past its own merger timescale — which the real pipeline never
    // produces (for mergers the window *is* the dynamical friction time;
    // for survivors it is shorter) and which the Python reference has no
    // notion of, since `StellarMassLoss`'s `Factor` is <= 1 by
    // construction there.
    Timeline { z, t, dt, log_host_mass: vec![13.0; 11], t_dyn_friction: 3.0 }
}

fn build_pipeline(cosmo: &Planck15) -> BaryonicPipeline {
    BaryonicPipeline::new(
        Box::new(TomczakFormSfr::ce()),
        Box::new(Wetzel13::new()),
        Box::new(StewartScaling::from_cosmology(cosmo)),
        Box::new(Cattaneo11),
    )
}

fn build_uncapped_pipeline() -> BaryonicPipeline {
    BaryonicPipeline::new(
        Box::new(TomczakFormSfr::ce()),
        Box::new(Wetzel13::new()),
        Box::new(UncappedGas),
        Box::new(Cattaneo11),
    )
}

fn build_galaxy(z0: f64) -> SatelliteState {
    SatelliteState {
        log_sm_infall: 10.0,
        log_host_mass_infall: 13.0,
        log_sat_mass_infall: 11.5,
        z_infall: z0,
        pre_quenched: false,
    }
}

/// `BaryonicPipeline::evolve` only forwards `ctx` to the SFR model, and
/// `TomczakFormSfr` (every pipeline built above) is memoryless, so a
/// single flat point is enough to satisfy the trait's context argument.
fn flat_track() -> GrowthTrack {
    GrowthTrack { z: vec![0.0], log_mass: vec![13.0] }
}

fn assert_matches(history: &[f64], expected: &[f64], tol: f64) {
    assert_eq!(
        history.len(),
        expected.len(),
        "trajectory length changed -- the regression values no longer describe the whole output"
    );
    for (i, (&got, &want)) in history.iter().zip(expected.iter()).enumerate() {
        assert!((got - want).abs() < tol, "step {i}: got {got}, want {want}");
    }
}

/// Generated by `Scripts/Validation/reference_baryonic.py --age-grid ...`
/// from `Functions_c.pyx::Starformation_c` with `Scatter_On = 0`.
const PYTHON_UNSTRIPPED: [f64; 11] = [
    10.0000000000,
    10.0278564415,
    10.0552312867,
    10.0825115484,
    10.1098555718,
    10.1373443940,
    10.1639858895,
    10.1709886561,
    10.1718105998,
    10.1708481445,
    10.1694998250,
];

/// Measured against the `PipGrylls` branch, i.e. with the `Strip_f =
/// Strip_f*2` that `StellarMassLoss` applies there. The `master`
/// baseline this replaced ran from 10.0090146458 at step 1 down to
/// 9.7859900851 at step 10; doubling the stripping takes the same
/// satellite to 9.4004874451, a further 0.39 dex of stellar mass lost
/// over 2.7 Gyr. See `Cattaneo11`'s doc comment.
const PYTHON_STRIPPED: [f64; 11] = [
    10.0000000000,
    9.9902294070,
    9.9754491005,
    9.9552708269,
    9.9288438964,
    9.8949243455,
    9.8558245594,
    9.7812316257,
    9.6818329937,
    9.5573424135,
    9.4004874451,
];

#[test]
fn unstripped_noiseless_trajectory_matches_the_cython_when_the_gas_cap_is_neutralised() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_uncapped_pipeline();
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng = StdRng::seed_from_u64(1);
    let history = pipeline.evolve(&galaxy, &timeline, false, false, &ctx, &mut rng);
    assert_matches(&history.log_sm, &PYTHON_UNSTRIPPED, 1e-8);
}

/// The stripped trajectory matches the Cython *with the real gas model
/// in place*, because a satellite losing mass never accumulates enough
/// newly-formed stars to hit the ceiling. That it agrees to 1e-9 over
/// all eleven steps with no adjustment is the cleanest single check
/// that the port is faithful.
#[test]
fn stripped_noiseless_trajectory_matches_the_cython_exactly() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng = StdRng::seed_from_u64(1);
    let history = pipeline.evolve(&galaxy, &timeline, true, false, &ctx, &mut rng);
    assert_matches(&history.log_sm, &PYTHON_STRIPPED, 1e-8);
}

/// PORT-FIX A6: the gas supply actually limits star formation here,
/// where in the Python it never can. This pins the Rust's own behaviour
/// so the correction cannot silently revert.
#[test]
fn the_gas_supply_cap_engages_and_suppresses_growth() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);

    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng = StdRng::seed_from_u64(1);
    let capped = build_pipeline(&cosmo).evolve(&galaxy, &timeline, false, false, &ctx, &mut rng);
    let mut rng = StdRng::seed_from_u64(1);
    let uncapped = build_uncapped_pipeline().evolve(&galaxy, &timeline, false, false, &ctx, &mut rng);

    // The two agree until the galaxy has formed enough new stars to
    // exhaust its gas, then diverge.
    for i in 0..=6 {
        assert!(
            (capped.log_sm[i] - uncapped.log_sm[i]).abs() < 1e-12,
            "step {i}: the cap should not have engaged yet"
        );
    }
    assert!(
        *capped.log_sm.last().unwrap() < *uncapped.log_sm.last().unwrap() - 0.01,
        "the gas cap should measurably suppress final mass: {} vs {}",
        capped.log_sm.last().unwrap(),
        uncapped.log_sm.last().unwrap()
    );

    let expected = [
        10.0000000000,
        10.0278564415,
        10.0552312867,
        10.0825115484,
        10.1098555718,
        10.1373443940,
        10.1639858895,
        10.1614012460,
        10.1595470425,
        10.1580638038,
        10.1568146930,
    ];
    assert_matches(&capped.log_sm, &expected, 1e-8);
}

#[test]
fn stripped_satellite_ends_lower_mass_than_unstripped() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng_a = StdRng::seed_from_u64(1);
    let unstripped = pipeline.evolve(&galaxy, &timeline, false, false, &ctx, &mut rng_a);
    let mut rng_b = StdRng::seed_from_u64(1);
    let stripped = pipeline.evolve(&galaxy, &timeline, true, false, &ctx, &mut rng_b);

    assert!(*stripped.log_sm.last().unwrap() < *unstripped.log_sm.last().unwrap());
}

#[test]
fn scatter_on_gives_reproducible_results_for_a_fixed_seed() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng1 = StdRng::seed_from_u64(99);
    let h1 = pipeline.evolve(&galaxy, &timeline, false, true, &ctx, &mut rng1);
    let mut rng2 = StdRng::seed_from_u64(99);
    let h2 = pipeline.evolve(&galaxy, &timeline, false, true, &ctx, &mut rng2);

    // Exact equality is deliberate here, not an oversight. The claim
    // under test is specifically that an identical seed reproduces
    // bit-identical output -- same process, same code path, same
    // deterministic IEEE operations. Comparing within an epsilon would
    // weaken this into "roughly similar", which is no longer a
    // determinism test at all.
    assert_eq!(h1.log_sm, h2.log_sm);
}

/// With scatter off the gas ceiling must be the relation's mean, not a
/// draw -- otherwise "deterministic mode" still has one live stochastic
/// source and the three-way comparison's strong claim is unfounded.
#[test]
fn noiseless_evolution_does_not_consume_randomness() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);

    let mut rng_a = StdRng::seed_from_u64(1);
    let a = pipeline.evolve(&galaxy, &timeline, false, false, &ctx, &mut rng_a);
    let mut rng_b = StdRng::seed_from_u64(12345);
    let b = pipeline.evolve(&galaxy, &timeline, false, false, &ctx, &mut rng_b);

    assert_eq!(a.log_sm, b.log_sm, "a noiseless run must not depend on the seed");
}

/// A two-step timeline, chosen so the Moster+2018 recycling loop
/// (`i > 0 && i < n - 1`) cannot run for any `i`: with `n = 2` the only
/// indices are 0 (fails `i > 0`) and 1 (fails `i < 1`). That makes the
/// mass returned to the ISM identically zero, so the step-0 mass budget
/// closes on stripping and star formation alone -- which is what
/// `stripped_mass_closes_the_budget` needs to check `stripped` against
/// something other than a restatement of its own formula.
fn build_two_step_timeline(cosmo: &Planck15) -> Timeline {
    let z = vec![1.0, 0.95];
    let t: Vec<f64> = z.iter().map(|&zi| cosmo.age(zi)).collect();
    let dt = vec![t[1] - t[0], t[1] - t[0]];
    Timeline { z, t, dt, log_host_mass: vec![13.0; 2], t_dyn_friction: 3.0 }
}

/// The stripped mass must be exactly the mass that left the satellite.
///
/// With recycling suppressed (see `build_two_step_timeline`) the pipeline's
/// own step-0 budget is
///
/// ```text
/// M(1) = M(0) - stripped(0) + SFH(0)
/// ```
///
/// and `SFH(0)` is recoverable from the returned sSFR
/// (`log_ssfr[i] = log10(SFH[i] / (dt[i] * 1e9 * M(i)))`), so every term
/// is reconstructed from the public output rather than from the
/// implementation. A sign error, an off-by-one in the `strip_factor`
/// difference, or reporting the cumulative bound fraction instead of the
/// per-step loss all break this.
#[test]
fn stripped_mass_closes_the_budget() {
    let cosmo = Planck15::new();
    let timeline = build_two_step_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);
    let mut rng = StdRng::seed_from_u64(4);

    let h = pipeline.evolve(&galaxy, &timeline, true, false, &ctx, &mut rng);

    let m0 = 10f64.powf(h.log_sm[0]);
    let m1 = 10f64.powf(h.log_sm[1]);
    let sfh0 = 10f64.powf(h.log_ssfr[0]) * timeline.dt[0] * 1.0e9 * m0;

    let expected = m0 - h.stripped[0] + sfh0;
    let rel = (m1 - expected).abs() / m1;
    assert!(
        rel < 1e-12,
        "step-0 mass budget does not close: M(1)={m1}, M(0)-stripped+SFH={expected} \
         (M(0)={m0}, stripped={}, SFH={sfh0})",
        h.stripped[0]
    );

    assert!(h.stripped[0] > 0.0, "a stripped satellite must lose mass, got {}", h.stripped[0]);
    assert!(h.stripped.iter().all(|s| s.is_finite() && *s >= 0.0), "{:?}", h.stripped);
    assert_eq!(h.stripped.len(), h.log_sm.len(), "one stripped-mass entry per timeline step");
}

/// Stripping off means nothing is stripped -- the ICL accumulator must
/// stay empty rather than quietly banking the no-stripping baseline.
#[test]
fn no_stripping_banks_no_mass() {
    let cosmo = Planck15::new();
    let timeline = build_timeline(&cosmo);
    let galaxy = build_galaxy(timeline.z[0]);
    let pipeline = build_pipeline(&cosmo);
    let track = flat_track();
    let ctx = AccretionContext::central(&track, &cosmo, MassDefinition::Vir);
    let mut rng = StdRng::seed_from_u64(4);

    let h = pipeline.evolve(&galaxy, &timeline, false, false, &ctx, &mut rng);

    assert!(h.stripped.iter().all(|&s| s == 0.0), "{:?}", h.stripped);
}
